name: Upload To Azure Blob Storage
on:
  create:
    branches:
      - master

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          source_dir: 'topics'
          container_name: 'markdown'
          connection_string: ${{ secrets.StorageConnectionString }}
          extra_args: '--pattern *.md'
