name: Upload To Azure Blob Storage
on:
  create:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: CamiloGarciaLaRotta/watermelon-http-client@v1.4
        with:
          url: https://notificationsendpoint.azurewebsites.net/api/send
          method: post
          headers: '{ "x-functions-key": "${{ secrets.NotifyFunctionKey }}" }'
          data:  '{	"title": "GitHub action started", "body": "New markdown file found", "channel": "WordsOfTheDay" }'
  upload-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          source_dir: 'topics'
          container_name: 'markdown'
          connection_string: ${{ secrets.StorageConnectionString }}
  upload-parts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          source_dir: 'parts'
          container_name: 'parts'
          connection_string: ${{ secrets.StorageConnectionString }}
